name: bridge_role_01
from_domain: 27
to_domain: 100

topics:
  # =============================================================

  /Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    from_domain: 27
    to_domain: 100
    remap: /CAV_27/Ego_pose   # <--- 핵심! Main이 식별할 수 있게 이름표 붙이기

  # 2. 정지 명령
  /CAV_27/cmd_stop:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 27
    remap: /CAV_01/cmd_stop

  # 3. 경로 변경 명령
  /CAV_27/change_waypoint:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 27
    remap: /CAV_01/change_waypoint

  # 4. 주변 차량 속도 정보
  /CAV_27/hv_vel:
    type: std_msgs/msg/Float32
    from_domain: 100
    to_domain: 27
    remap: /CAV_01/hv_vel

  # 5. 회전교차로 인식 정보
  /CAV_27/is_roundabout:
    type: std_msgs/msg/Bool
    from_domain: 100
    to_domain: 27
    remap: /CAV_01/is_roundabout