name: domain_manage
from_domain: 100    # 기본값: Main(100) -> Stanley(1) 방향

topics:
  # 1. CAV 01
  /cav1/cmd_stop:
    type: std_msgs/msg/Bool
    to_domain: 1

  /cav1/change_waypoint:
    type: std_msgs/msg/Bool
    to_domain: 1

  /cav1/hv_vel:
    type: std_msgs/msg/Float32
    to_domain: 1

  /cav1/is_roundabout:
    type: std_msgs/msg/Bool
    to_domain: 1

  # 2. CAV 02 
  /cav2/cmd_stop:
    type: std_msgs/msg/Bool
    to_domain: 2

  /cav2/change_waypoint:
    type: std_msgs/msg/Bool
    to_domain: 2

  /cav2/hv_vel:
    type: std_msgs/msg/Float32
    to_domain: 2

  /cav2/is_roundabout:
    type: std_msgs/msg/Bool
    to_domain: 2

  # 3. CAV 03 
  /cav3/cmd_stop:
    type: std_msgs/msg/Bool
    to_domain: 3

  /cav3/change_waypoint:
    type: std_msgs/msg/Bool
    to_domain: 3

  /cav3/hv_vel:
    type: std_msgs/msg/Float32
    to_domain: 3

  /cav3/is_roundabout:
    type: std_msgs/msg/Bool
    to_domain: 3

  # 4. CAV 04 
  /cav4/cmd_stop:
    type: std_msgs/msg/Bool
    to_domain: 4

  /cav4/change_waypoint:
    type: std_msgs/msg/Bool
    to_domain: 4

  /cav4/hv_vel:
    type: std_msgs/msg/Float32
    to_domain: 4

  /cav4/is_roundabout:
    type: std_msgs/msg/Bool
    to_domain: 4